# Package Overview
package_name: catvsdog_model

# Data Files
train_path: train
validation_path: validation
test_path: test


model_name: catvsdog_model
model_save_file: catvsdog__model_output_v

# Feature engineering parameters
image_size: 
  - 180
  - 180
batch_size: 32
scaling_factor: 255.0
rotation: 0.1
zoom: 0.2
flip: horizontal

# Set the random seed
random_state: 42

# Alogrithm parameters
input_shape: 
  - 180
  - 180
  - 3
epochs: 10
optimizer: rmsprop
loss: binary_crossentropy
accuracy_metric: accuracy
verbose: 1
earlystop: 0
monitor: val_loss
save_best_only: True

# Mappings for calss labels
label_mappings: 
  0: cat
  1: dog